# "aootype", "aookey", "aooname", "aoosort", "welsh", "master", "GSS", "ISO3166-1", "ISO3166-2:GB", "ContinentCode", "oldCode"
CC_AOO_CODES = [
    ["A", 1, "THROUGHOUT ENGLAND AND WALES", "At least 10 authorities in England and Wales", "N", None, "K04000001", "GB", "GB-EAW", "EU", "941"],
    ["A", 2, "THROUGHOUT ENGLAND", "At least 10 authorities in England only", "N", None, "E92000001", "GB", "GB-ENG", "EU", "921"],
    ["A", 3, "THROUGHOUT WALES", "At least 10 authorities in Wales only", "N", None, "W92000004", "GB", "GB-WLS", "EU", "924"],
    ["A", 4, "THROUGHOUT LONDON", "At least 10 authorities in Greater London", "N", None, "E12000007", "GB", None, "EU", "H"],
    ["B", 1, "BRACKNELL FOREST", "BRACKNELL FOREST", "N", None, "E06000036", "GB", "GB-BRC", "EU", "00MA"],
    ["B", 2, "WEST BERKSHIRE", "WEST BERKSHIRE", "N", None, "E06000037", "GB", "GB-WBK", "EU", "00MB"],
    ["B", 3, "READING", "READING", "N", None, "E06000038", "GB", "GB-RDG", "EU", "00MC"],
    ["B", 4, "SLOUGH", "SLOUGH", "N", None, "E06000039", "GB", "GB-SLG", "EU", "00MD"],
    ["B", 5, "WINDSOR AND MAIDENHEAD", "WINDSOR AND MAIDENHEAD", "N", None, "E06000040", "GB", "GB-WNM", "EU", "00ME"],
    ["B", 6, "WOKINGHAM", "WOKINGHAM", "N", None, "E06000041", "GB", "GB-WOK", "EU", "00MF"],
    ["B", 7, "BARKING AND DAGENHAM", "BARKING AND DAGENHAM", "N", "20", "E09000002", "GB", "GB-BDG", "EU", "00AB"],
    ["B", 8, "BARNET", "BARNET", "N", "20", "E09000003", "GB", "GB-BNE", "EU", "00AC"],
    ["B", 9, "BEXLEY", "BEXLEY", "N", "20", "E09000004", "GB", "GB-BEX", "EU", "00AD"],
    ["B", 10, "BRENT", "BRENT", "N", "20", "E09000005", "GB", "GB-BEN", "EU", "00AE"],
    ["B", 11, "BROMLEY", "BROMLEY", "N", "20", "E09000006", "GB", "GB-BRY", "EU", "00AF"],
    ["B", 12, "CAMDEN", "CAMDEN", "N", "20", "E09000007", "GB", "GB-CMD", "EU", "00AG"],
    ["B", 13, "CITY OF LONDON", "CITY OF LONDON", "N", "20", "E09000001", "GB", "GB-LND", "EU", "00AA"],
    ["B", 14, "CITY OF WESTMINSTER", "WESTMINSTER", "N", "20", "E09000033", "GB", "GB-WSM", "EU", "00BK"],
    ["B", 15, "CROYDON", "CROYDON", "N", "20", "E09000008", "GB", "GB-CRY", "EU", "00AH"],
    ["B", 16, "EALING", "EALING", "N", "20", "E09000009", "GB", "GB-EAL", "EU", "00AJ"],
    ["B", 17, "ENFIELD", "ENFIELD", "N", "20", "E09000010", "GB", "GB-ENF", "EU", "00AK"],
    ["B", 18, "GREENWICH", "GREENWICH", "N", "20", "E09000011", "GB", "GB-GRE", "EU", "00AL"],
    ["B", 19, "HACKNEY", "HACKNEY", "N", "20", "E09000012", "GB", "GB-HCK", "EU", "00AM"],
    ["B", 20, "HAMMERSMITH AND FULHAM", "HAMMERSMITH AND FULHAM", "N", "20", "E09000013", "GB", "GB-HMF", "EU", "00AN"],
    ["B", 21, "HARINGEY", "HARINGEY", "N", "20", "E09000014", "GB", "GB-HRY", "EU", "00AP"],
    ["B", 22, "HARROW", "HARROW", "N", "20", "E09000015", "GB", "GB-HRW", "EU", "00AQ"],
    ["B", 23, "HAVERING", "HAVERING", "N", "20", "E09000016", "GB", "GB-HAV", "EU", "00AR"],
    ["B", 24, "HILLINGDON", "HILLINGDON", "N", "20", "E09000017", "GB", "GB-HIL", "EU", "00AS"],
    ["B", 25, "HOUNSLOW", "HOUNSLOW", "N", "20", "E09000018", "GB", "GB-HNS", "EU", "00AT"],
    ["B", 26, "ISLINGTON", "ISLINGTON", "N", "20", "E09000019", "GB", "GB-ISL", "EU", "00AU"],
    ["B", 27, "KENSINGTON AND CHELSEA", "KENSINGTON AND CHELSEA", "N", "20", "E09000020", "GB", "GB-KEC", "EU", "00AW"],
    ["B", 28, "KINGSTON UPON THAMES", "KINGSTON UPON THAMES", "N", "20", "E09000021", "GB", "GB-KTT", "EU", "00AX"],
    ["B", 29, "LAMBETH", "LAMBETH", "N", "20", "E09000022", "GB", "GB-LBH", "EU", "00AY"],
    ["B", 30, "LEWISHAM", "LEWISHAM", "N", "20", "E09000023", "GB", "GB-LEW", "EU", "00AZ"],
    ["B", 31, "MERTON", "MERTON", "N", "20", "E09000024", "GB", "GB-MRT", "EU", "00BA"],
    ["B", 32, "NEWHAM", "NEWHAM", "N", "20", "E09000025", "GB", "GB-NWM", "EU", "00BB"],
    ["B", 33, "REDBRIDGE", "REDBRIDGE", "N", "20", "E09000026", "GB", "GB-RDB", "EU", "00BC"],
    ["B", 34, "RICHMOND UPON THAMES", "RICHMOND UPON THAMES", "N", "20", "E09000027", "GB", "GB-RIC", "EU", "00BD"],
    ["B", 35, "SOUTHWARK", "SOUTHWARK", "N", "20", "E09000028", "GB", "GB-SWK", "EU", "00BE"],
    ["B", 36, "SUTTON", "SUTTON", "N", "20", "E09000029", "GB", "GB-STN", "EU", "00BF"],
    ["B", 37, "TOWER HAMLETS", "TOWER HAMLETS", "N", "20", "E09000030", "GB", "GB-TWH", "EU", "00BG"],
    ["B", 38, "WALTHAM FOREST", "WALTHAM FOREST", "N", "20", "E09000031", "GB", "GB-WFT", "EU", "00BH"],
    ["B", 39, "WANDSWORTH", "WANDSWORTH", "N", "20", "E09000032", "GB", "GB-WND", "EU", "00BJ"],
    ["B", 40, "BOLTON", "BOLTON", "N", "21", "E08000001", "GB", "GB-BOL", "EU", "00BL"],
    ["B", 41, "BURY", "BURY", "N", "21", "E08000002", "GB", "GB-BUR", "EU", "00BM"],
    ["B", 42, "MANCHESTER CITY", "MANCHESTER", "N", "21", "E08000003", "GB", "GB-MAN", "EU", "00BN"],
    ["B", 43, "OLDHAM", "OLDHAM", "N", "21", "E08000004", "GB", "GB-OLD", "EU", "00BP"],
    ["B", 44, "ROCHDALE", "ROCHDALE", "N", "21", "E08000005", "GB", "GB-RCH", "EU", "00BQ"],
    ["B", 45, "SALFORD CITY", "SALFORD", "N", "21", "E08000006", "GB", "GB-SLF", "EU", "00BR"],
    ["B", 46, "STOCKPORT", "STOCKPORT", "N", "21", "E08000007", "GB", "GB-SKP", "EU", "00BS"],
    ["B", 47, "TAMESIDE", "TAMESIDE", "N", "21", "E08000008", "GB", "GB-TAM", "EU", "00BT"],
    ["B", 48, "TRAFFORD", "TRAFFORD", "N", "21", "E08000009", "GB", "GB-TRF", "EU", "00BU"],
    ["B", 49, "WIGAN", "WIGAN", "N", "21", "E08000010", "GB", "GB-WGN", "EU", "00BW"],
    ["B", 50, "KNOWSLEY", "KNOWSLEY", "N", "33", "E08000011", "GB", "GB-KWL", "EU", "00BX"],
    ["B", 51, "LIVERPOOL CITY", "LIVERPOOL", "N", "33", "E08000012", "GB", "GB-LIV", "EU", "00BY"],
    ["B", 52, "SEFTON", "SEFTON", "N", "33", "E08000014", "GB", "GB-SFT", "EU", "00CA"],
    ["B", 53, "ST HELENS", "ST HELENS", "N", "33", "E08000013", "GB", "GB-SHN", "EU", "00BZ"],
    ["B", 54, "WIRRAL", "WIRRAL", "N", "33", "E08000015", "GB", "GB-WRL", "EU", "00CB"],
    ["B", 55, "BARNSLEY", "BARNSLEY", "N", "48", "E08000016", "GB", "GB-BNS", "EU", "00CC"],
    ["B", 56, "DONCASTER", "DONCASTER", "N", "48", "E08000017", "GB", "GB-DNC", "EU", "00CE"],
    ["B", 57, "ROTHERHAM", "ROTHERHAM", "N", "48", "E08000018", "GB", "GB-ROT", "EU", "00CF"],
    ["B", 58, "SHEFFIELD CITY", "SHEFFIELD", "N", "48", "E08000019", "GB", "GB-SHF", "EU", "00CG"],
    ["B", 59, "GATESHEAD", "GATESHEAD", "N", "52", "E08000037", "GB", "GB-GAT", "EU", "00CH"],
    ["B", 60, "NEWCASTLE UPON TYNE CITY", "NEWCASTLE UPON TYNE", "N", "52", "E08000021", "GB", "GB-NET", "EU", "00CJ"],
    ["B", 61, "NORTH TYNESIDE", "NORTH TYNESIDE", "N", "52", "E08000022", "GB", "GB-NTY", "EU", "00CK"],
    ["B", 62, "SOUTH TYNESIDE", "SOUTH TYNESIDE", "N", "52", "E08000023", "GB", "GB-STY", "EU", "00CL"],
    ["B", 63, "SUNDERLAND", "SUNDERLAND", "N", "52", "E08000024", "GB", "GB-SND", "EU", "00CM"],
    ["B", 64, "BIRMINGHAM CITY", "BIRMINGHAM", "N", "57", "E08000025", "GB", "GB-BIR", "EU", "00CN"],
    ["B", 65, "COVENTRY CITY", "COVENTRY", "N", "57", "E08000026", "GB", "GB-COV", "EU", "00CQ"],
    ["B", 66, "DUDLEY", "DUDLEY", "N", "57", "E08000027", "GB", "GB-DUD", "EU", "00CR"],
    ["B", 67, "SANDWELL", "SANDWELL", "N", "57", "E08000028", "GB", "GB-SAW", "EU", "00CS"],
    ["B", 68, "SOLIHULL", "SOLIHULL", "N", "57", "E08000029", "GB", "GB-SOL", "EU", "00CT"],
    ["B", 69, "WALSALL", "WALSALL", "N", "57", "E08000030", "GB", "GB-WLL", "EU", "00CU"],
    ["B", 70, "WOLVERHAMPTON", "WOLVERHAMPTON", "N", "57", "E08000031", "GB", "GB-WLV", "EU", "00CW"],
    ["B", 71, "BRADFORD CITY", "BRADFORD", "N", "59", "E08000032", "GB", "GB-BRD", "EU", "00CX"],
    ["B", 72, "CALDERDALE", "CALDERDALE", "N", "59", "E08000033", "GB", "GB-CLD", "EU", "00CY"],
    ["B", 73, "KIRKLEES", "KIRKLEES", "N", "59", "E08000034", "GB", "GB-KIR", "EU", "00CZ"],
    ["B", 74, "LEEDS CITY", "LEEDS", "N", "59", "E08000035", "GB", "GB-LDS", "EU", "00DA"],
    ["B", 75, "CITY OF WAKEFIELD", "WAKEFIELD", "N", "59", "E08000036", "GB", "GB-WKF", "EU", "00DB"],
    ["B", 76, "NOTTINGHAM CITY", "NOTTINGHAM", "N", None, "E06000018", "GB", "GB-NGM", "EU", "00FY"],
    ["B", 101, "CENTRAL BEDFORDSHIRE", "CENTRAL BEDFORDSHIRE", "N", None, "E06000056", "GB", "GB-CBF", "EU", "00KC"],
    ["B", 102, "BUCKINGHAMSHIRE", "BUCKINGHAMSHIRE", "N", None, "E10000002", "GB", "GB-BKM", "EU", "11"],
    ["B", 103, "CAMBRIDGESHIRE", "CAMBRIDGESHIRE", "N", None, "E10000003", "GB", "GB-CAM", "EU", "12"],
    ["B", 104, "CHESHIRE EAST", "CHESHIRE EAST", "N", None, "E06000049", "GB", "GB-CHE", "EU", "00EQ"],
    ["B", 105, "CORNWALL", "CORNWALL", "N", None, "E06000052", "GB", "GB-CON", "EU", "00HE"],
    ["B", 106, "CUMBRIA", "CUMBRIA", "N", None, "E10000006", "GB", "GB-CMA", "EU", "16"],
    ["B", 107, "DERBYSHIRE", "DERBYSHIRE", "N", None, "E10000007", "GB", "GB-DBY", "EU", "17"],
    ["B", 108, "DEVON", "DEVON", "N", None, "E10000008", "GB", "GB-DEV", "EU", "18"],
    ["B", 109, "DORSET", "DORSET", "N", None, "E10000009", "GB", "GB-DOR", "EU", "19"],
    ["B", 110, "DURHAM", "DURHAM", "N", None, "E06000047", "GB", "GB-DUR", "EU", "00EJ"],
    ["B", 111, "EAST SUSSEX", "EAST SUSSEX", "N", None, "E10000011", "GB", "GB-ESX", "EU", "21"],
    ["B", 112, "ESSEX", "ESSEX", "N", None, "E10000012", "GB", "GB-ESS", "EU", "22"],
    ["B", 113, "GLOUCESTERSHIRE", "GLOUCESTERSHIRE", "N", None, "E10000013", "GB", "GB-GLS", "EU", "23"],
    ["B", 114, "HAMPSHIRE", "HAMPSHIRE", "N", None, "E10000014", "GB", "GB-HAM", "EU", "24"],
    ["B", 115, "HERTFORDSHIRE", "HERTFORDSHIRE", "N", None, "E06000019", "GB", "GB-HRT", "EU", "00GA"],
    ["B", 116, "ISLE OF WIGHT", "ISLE OF WIGHT", "N", None, "E06000046", "GB", "GB-IOW", "EU", "00MW"],
    ["B", 117, "KENT", "KENT", "N", None, "E10000016", "GB", "GB-KEN", "EU", "29"],
    ["B", 118, "LANCASHIRE", "LANCASHIRE", "N", None, "E10000017", "GB", "GB-LAN", "EU", "30"],
    ["B", 119, "LEICESTERSHIRE", "LEICESTERSHIRE", "N", None, "E10000018", "GB", "GB-LEC", "EU", "31"],
    ["B", 120, "LINCOLNSHIRE", "LINCOLNSHIRE", "N", None, "E10000019", "GB", "GB-LIN", "EU", "32"],
    ["B", 121, "NORFOLK", "NORFOLK", "N", None, "E10000020", "GB", "GB-NFK", "EU", "33"],
    ["B", 122, "NORTH YORKSHIRE", "NORTH YORKSHIRE", "N", None, "E10000023", "GB", "GB-NYK", "EU", "36"],
    ["B", 123, "NORTHAMPTONSHIRE", "NORTHAMPTONSHIRE", "N", None, "E10000021", "GB", "GB-NTH", "EU", "34"],
    ["B", 124, "NORTHUMBERLAND", "NORTHUMBERLAND", "N", None, "E06000057", "GB", "GB-NBL", "EU", "00EM"],
    ["B", 125, "NOTTINGHAMSHIRE", "NOTTINGHAMSHIRE", "N", None, "E10000024", "GB", "GB-NTT", "EU", "37"],
    ["B", 126, "OXFORDSHIRE", "OXFORDSHIRE", "N", None, "E10000025", "GB", "GB-OXF", "EU", "38"],
    ["B", 127, "POWYS", "POWYS", "Y", None, "W06000023", "GB", "GB-POW", "EU", "00NN"],
    ["B", 128, "SHROPSHIRE", "SHROPSHIRE", "N", None, "E06000051", "GB", "GB-SHR", "EU", "00GG"],
    ["B", 129, "SOMERSET", "SOMERSET", "N", None, "E10000027", "GB", "GB-SOM", "EU", "40"],
    ["B", 130, "STAFFORDSHIRE", "STAFFORDSHIRE", "N", None, "E10000028", "GB", "GB-STS", "EU", "41"],
    ["B", 131, "SUFFOLK", "SUFFOLK", "N", None, "E10000029", "GB", "GB-SFK", "EU", "42"],
    ["B", 132, "SURREY", "SURREY", "N", None, "E10000030", "GB", "GB-SRY", "EU", "43"],
    ["B", 133, "WARWICKSHIRE", "WARWICKSHIRE", "N", None, "E10000031", "GB", "GB-WAR", "EU", "44"],
    ["B", 134, "WEST SUSSEX", "WEST SUSSEX", "N", None, "E10000032", "GB", "GB-WSX", "EU", "45"],
    ["B", 135, "WILTSHIRE", "WILTSHIRE", "N", None, "E06000054", "GB", "GB-WIL", "EU", "00HY"],
    ["B", 136, "NORTH SOMERSET", "NORTH SOMERSET", "N", None, "E06000024", "GB", "GB-NSM", "EU", "00HC"],
    ["B", 137, "BATH AND NORTH EAST SOMERSET", "BATH AND NORTH EAST SOMERSET", "N", None, "E06000022", "GB", "GB-BAS", "EU", "00HA"],
    ["B", 138, "SOUTH GLOUCESTERSHIRE", "SOUTH GLOUCESTERSHIRE", "N", None, "E06000025", "GB", "GB-SGC", "EU", "00HD"],
    ["B", 139, "BRISTOL CITY", "BRISTOL", "N", None, "E06000023", "GB", "GB-BST", "EU", "00HB"],
    ["B", 140, "HARTLEPOOL", "HARTLEPOOL", "N", None, "E06000001", "GB", "GB-HPL", "EU", "00EB"],
    ["B", 141, "MIDDLESBROUGH", "MIDDLESBROUGH", "N", None, "E06000002", "GB", "GB-MDB", "EU", "00EC"],
    ["B", 142, "REDCAR AND CLEVELAND", "REDCAR AND CLEVELAND", "N", None, "E06000003", "GB", "GB-RCC", "EU", "00EE"],
    ["B", 143, "STOCKTON-ON-TEES", "STOCKTON-ON-TEES", "N", None, "E06000004", "GB", "GB-STT", "EU", "00EF"],
    ["B", 144, "KINGSTON UPON HULL CITY", "KINGSTON UPON HULL", "N", None, "E06000010", "GB", "GB-KHL", "EU", "00FA"],
    ["B", 145, "NORTH LINCOLNSHIRE", "NORTH LINCOLNSHIRE", "N", None, "E06000013", "GB", "GB-NLN", "EU", "00FD"],
    ["B", 146, "NORTH EAST LINCOLNSHIRE", "NORTH EAST LINCOLNSHIRE", "N", None, "E06000012", "GB", "GB-NEL", "EU", "00FC"],
    ["B", 147, "EAST RIDING OF YORKSHIRE", "EAST RIDING OF YORKSHIRE", "N", None, "E06000011", "GB", "GB-ERY", "EU", "00FB"],
    ["B", 148, "CONWY", "CONWY", "Y", None, "W06000003", "GB", "GB-CWY", "EU", "00NE"],
    ["B", 149, "ISLE OF ANGLESEY", "ISLE OF ANGLESEY", "Y", None, "W06000001", "GB", "GB-AGY", "EU", "00NA"],
    ["B", 150, "BLAENAU GWENT", "BLAENAU GWENT", "Y", None, "W06000019", "GB", "GB-BGW", "EU", "00PL"],
    ["B", 151, "BRIDGEND", "BRIDGEND", "Y", None, "W06000013", "GB", "GB-BGE", "EU", "00PB"],
    ["B", 152, "CAERPHILLY", "CAERPHILLY", "Y", None, "W06000018", "GB", "GB-CAY", "EU", "00PK"],
    ["B", 153, "CARDIFF", "CARDIFF", "Y", None, "W06000015", "GB", "GB-CRF", "EU", "00PT"],
    ["B", 154, "CEREDIGION", "CEREDIGION", "Y", None, "W06000008", "GB", "GB-CGN", "EU", "00NQ"],
    ["B", 155, "CARMARTHENSHIRE", "CARMARTHENSHIRE", "Y", None, "W06000010", "GB", "GB-CMN", "EU", "00NU"],
    ["B", 156, "DENBIGHSHIRE", "DENBIGHSHIRE", "Y", None, "W06000004", "GB", "GB-DEN", "EU", "00NG"],
    ["B", 157, "FLINTSHIRE", "FLINTSHIRE", "Y", None, "W06000005", "GB", "GB-FLN", "EU", "00NJ"],
    ["B", 158, "MERTHYR TYDFIL", "MERTHYR TYDFIL", "Y", None, "W06000024", "GB", "GB-MTY", "EU", "00PH"],
    ["B", 159, "MONMOUTHSHIRE", "MONMOUTHSHIRE", "Y", None, "W06000021", "GB", "GB-MON", "EU", "00PP"],
    ["B", 160, "NEATH PORT TALBOT", "NEATH PORT TALBOT", "Y", None, "W06000012", "GB", "GB-NTL", "EU", "00NZ"],
    ["B", 161, "NEWPORT CITY", "NEWPORT", "Y", None, "W06000022", "GB", "GB-NWP", "EU", "00PR"],
    ["B", 162, "PEMBROKESHIRE", "PEMBROKESHIRE", "Y", None, "W06000009", "GB", "GB-PEM", "EU", "00NS"],
    ["B", 163, "PLYMOUTH CITY", "PLYMOUTH", "N", None, "E06000026", "GB", "GB-PLY", "EU", "00HG"],
    ["B", 164, "CITY OF SWANSEA", "SWANSEA", "Y", None, "W06000011", "GB", "GB-SWA", "EU", "00NX"],
    ["B", 165, "VALE OF GLAMORGAN", "VALE OF GLAMORGAN", "Y", None, "W06000014", "GB", "GB-VGL", "EU", "00PD"],
    ["B", 166, "THURROCK", "THURROCK", "N", None, "E06000034", "GB", "GB-THR", "EU", "00KG"],
    ["B", 167, "WREXHAM", "WREXHAM", "Y", None, "W06000006", "GB", "GB-WRX", "EU", "00NL"],
    ["B", 168, "HALTON", "HALTON", "N", None, "E06000006", "GB", "GB-HAL", "EU", "00ET"],
    ["B", 169, "GWYNEDD", "GWYNEDD", "Y", None, "W06000002", "GB", "GB-GWN", "EU", "00NC"],
    ["B", 170, "CITY OF YORK", "YORK", "N", None, "E06000014", "GB", "GB-YOR", "EU", "00FF"],
    ["B", 171, "TORFAEN", "TORFAEN", "Y", None, "W06000020", "GB", "GB-TOF", "EU", "00PM"],
    ["B", 172, "WARRINGTON", "WARRINGTON", "N", None, "E06000007", "GB", "GB-WRT", "EU", "00EU"],
    ["B", 173, "RHONDDA CYNON TAFF", "RHONDDA CYNON TAFF", "Y", None, "W06000016", "GB", "GB-RCT", "EU", "00PF"],
    ["B", 174, "LUTON", "LUTON", "N", None, "E06000032", "GB", "GB-LUT", "EU", "00KA"],
    ["B", 175, "MILTON KEYNES", "MILTON KEYNES", "N", None, "E06000042", "GB", "GB-MIK", "EU", "00MG"],
    ["B", 176, "DERBY CITY", "DERBY", "N", None, "E06000015", "GB", "GB-DER", "EU", "00FK"],
    ["B", 177, "BOURNEMOUTH", "BOURNEMOUTH", "N", None, "E06000028", "GB", "GB-BMH", "EU", "00HN"],
    ["B", 178, "POOLE", "POOLE", "N", None, "E06000029", "GB", "GB-POL", "EU", "00HP"],
    ["B", 179, "DARLINGTON", "DARLINGTON", "N", None, "E06000005", "GB", "GB-DAL", "EU", "00EH"],
    ["B", 180, "BRIGHTON AND HOVE", "BRIGHTON AND HOVE", "N", None, "E06000043", "GB", "GB-BNH", "EU", "00ML"],
    ["B", 181, "SOUTHAMPTON CITY", "SOUTHAMPTON", "N", None, "E06000045", "GB", "GB-STH", "EU", "00MS"],
    ["B", 182, "PORTSMOUTH CITY", "PORTSMOUTH", "N", None, "E06000044", "GB", "GB-POR", "EU", "00MR"],
    ["B", 183, "LEICESTER CITY", "LEICESTER", "N", None, "E06000016", "GB", "GB-LCE", "EU", "00FN"],
    ["B", 184, "RUTLAND", "RUTLAND", "N", None, "E06000017", "GB", "GB-RUT", "EU", "00FP"],
    ["B", 185, "STOKE-ON-TRENT CITY", "STOKE-ON-TRENT", "N", None, "E06000021", "GB", "GB-STE", "EU", "00GL"],
    ["B", 186, "SWINDON", "SWINDON", "N", None, "E06000030", "GB", "GB-SWD", "EU", "00HX"],
    ["B", 187, "BLACKBURN WITH DARWEN", "BLACKBURN & DARWEN", "N", None, "E06000008", "GB", "GB-BBD", "EU", "00EX"],
    ["B", 188, "BLACKPOOL", "BLACKPOOL", "N", None, "E06000009", "GB", "GB-BPL", "EU", "00EY"],
    ["B", 189, "SOUTHEND-ON-SEA", "SOUTHEND-ON-SEA", "N", None, "E06000033", "GB", "GB-SOS", "EU", "00KF"],
    ["B", 190, "TELFORD & WREKIN", "THE WREKIN", "N", None, "E06000020", "GB", "GB-TFW", "EU", "00GF"],
    ["B", 191, "PETERBOROUGH CITY", "PETERBOROUGH", "N", None, "E06000031", "GB", "GB-PTE", "EU", "00JA"],
    ["B", 192, "HEREFORDSHIRE", "HEREFORDSHIRE", "N", None, "E06000019", "GB", "GB-HEF", "EU", "00GA"],
    ["B", 193, "WORCESTERSHIRE", "WORCESTERSHIRE", "N", None, "E10000034", "GB", "GB-WOR", "EU", "47"],
    ["B", 194, "MEDWAY", "MEDWAY", "N", None, "E06000035", "GB", "GB-MDW", "EU", "00LC"],
    ["B", 195, "ISLES OF SCILLY", "ISLES OF SCILLY", "N", None, "E06000053", "GB", "GB-IOS", "EU", "00HF"],
    ["B", 196, "TORBAY", "TORBAY", "N", None, "E06000027", "GB", "GB-TOB", "EU", "00HH"],
    ["B", 197, "CHESHIRE WEST & CHESTER", "CHESHIRE WEST & CHESTER", "N", None, "E06000050", "GB", "GB-CHW", "EU", "00EW"],
    ["B", 198, "BEDFORD", "BEDFORD", "N", None, "E06000055", "GB", "GB-BDF", "EU", "00KB"],
    ["C", 20, "GREATER LONDON", "GREATER LONDON", "N", None, "E12000007", "GB", None, "EU", "H"],
    ["C", 21, "GREATER MANCHESTER", "GREATER MANCHESTER", "N", None, "E11000001", "GB", None, "EU", "0"],
    ["C", 33, "MERSEYSIDE", "MERSEYSIDE", "N", None, "E11000002", "GB", None, "EU", "0"],
    ["C", 48, "SOUTH YORKSHIRE", "SOUTH YORKSHIRE", "N", None, "E11000003", "GB", None, "EU", "0"],
    ["C", 52, "TYNE AND WEAR", "TYNE AND WEAR", "N", None, "E11000007", "GB", None, "EU", "0"],
    ["C", 57, "WEST MIDLANDS", "WEST MIDLANDS", "N", None, "E11000005", "GB", None, "EU", "0"],
    ["C", 59, "WEST YORKSHIRE", "WEST YORKSHIRE", "N", None, "E11000006", "GB", None, "EU", "0"],
    ["D", 1, "AFGHANISTAN", "AFGHANISTAN", "N", "2", None, "AF", None, "AS", None],
    ["D", 2, "ALBANIA", "ALBANIA", "N", "3", None, "AL", None, "EU", None],
    ["D", 3, "ALGERIA", "ALGERIA", "N", "1", None, "DZ", None, "AF", None],
    ["D", 5, "ANDORRA", "ANDORRA", "N", "3", None, "AD", None, "EU", None],
    ["D", 6, "ANGOLA", "ANGOLA", "N", "1", None, "AO", None, "AF", None],
    ["D", 9, "ANTIGUA AND BARBUDA", "ANTIGUA AND BARBUDA", "N", "4", None, "AG", None, "NA", None],
    ["D", 10, "ARGENTINA", "ARGENTINA", "N", "5", None, "AR", None, "SA", None],
    ["D", 11, "ARMENIA", "ARMENIA", "N", "2", None, "AM", None, "AS", None],
    ["D", 13, "AUSTRALIA", "AUSTRALIA", "N", "6", None, "AU", None, "OC", None],
    ["D", 14, "AUSTRIA", "AUSTRIA", "N", "3", None, "AT", None, "EU", None],
    ["D", 15, "AZERBAIJAN", "AZERBAIJAN", "N", "3", None, "AZ", None, "EU", None],
    ["D", 17, "BAHAMAS", "BAHAMAS", "N", "4", None, "BS", None, "NA", None],
    ["D", 18, "BAHRAIN", "BAHRAIN", "N", "2", None, "BH", None, "AS", None],
    ["D", 19, "BANGLADESH", "BANGLADESH", "N", "2", None, "BD", None, "AS", None],
    ["D", 20, "BARBADOS", "BARBADOS", "N", "4", None, "BB", None, "NA", None],
    ["D", 21, "BELARUS", "BELARUS", "N", "3", None, "BY", None, "EU", None],
    ["D", 22, "BELGIUM", "BELGIUM", "N", "3", None, "BE", None, "EU", None],
    ["D", 23, "BELIZE", "BELIZE", "N", "4", None, "BZ", None, "NA", None],
    ["D", 24, "BENIN", "BENIN", "N", "1", None, "BJ", None, "AF", None],
    ["D", 26, "BHUTAN", "BHUTAN", "N", "2", None, "BT", None, "AS", None],
    ["D", 27, "BOLIVIA", "BOLIVIA", "N", "5", None, "BO", None, "SA", None],
    ["D", 28, "BOSNIA-HERZEGOVINA", "BOSNIA-HERZEGOVINA", "N", "3", None, "BA", None, "EU", None],
    ["D", 29, "BOTSWANA", "BOTSWANA", "N", "1", None, "BW", None, "AF", None],
    ["D", 30, "BRAZIL", "BRAZIL", "N", "5", None, "BR", None, "SA", None],
    ["D", 31, "BRUNEI", "BRUNEI", "N", "2", None, "BN", None, "AS", None],
    ["D", 32, "BULGARIA", "BULGARIA", "N", "3", None, "BG", None, "EU", None],
    ["D", 33, "BURKINA FASO", "BURKINA FASO", "N", "1", None, "BF", None, "AF", None],
    ["D", 34, "BURUNDI", "BURUNDI", "N", "1", None, "BI", None, "AF", None],
    ["D", 35, "CAMBODIA", "CAMBODIA", "N", "2", None, "KH", None, "AS", None],
    ["D", 36, "CAMEROON", "CAMEROON", "N", "1", None, "CM", None, "AF", None],
    ["D", 37, "CANADA", "CANADA", "N", "4", None, "CA", None, "NA", None],
    ["D", 38, "CAPE VERDE", "CAPE VERDE", "N", "3", None, "CV", None, "EU", None],
    ["D", 40, "CENTRAL AFRICAN REPUBLIC", "CENTRAL AFRICAN REPUBLIC", "N", "1", None, "CF", None, "AF", None],
    ["D", 41, "CHAD", "CHAD", "N", "1", None, "TD", None, "AF", None],
    ["D", 42, "CHILE", "CHILE", "N", "5", None, "CL", None, "SA", None],
    ["D", 43, "CHINA", "CHINA", "N", "2", None, "CN", None, "AS", None],
    ["D", 44, "COLOMBIA", "COLOMBIA", "N", "5", None, "CO", None, "SA", None],
    ["D", 45, "COMOROS", "COMOROS", "N", "1", None, "KM", None, "AF", None],
    ["D", 46, "REPUBLIC OF CONGO", "CONGO", "N", "1", None, "CG", None, "AF", None],
    ["D", 48, "COSTA RICA", "COSTA RICA", "N", "4", None, "CR", None, "NA", None],
    ["D", 49, "CROATIA", "CROATIA", "N", "3", None, "HR", None, "EU", None],
    ["D", 50, "CUBA", "CUBA", "N", "4", None, "CU", None, "NA", None],
    ["D", 51, "CYPRUS", "CYPRUS", "N", "3", None, "CY", None, "EU", None],
    ["D", 52, "CZECH REPUBLIC", "CZECH REPUBLIC", "N", "3", None, "CZ", None, "EU", None],
    ["D", 53, "DENMARK", "DENMARK", "N", "3", None, "DK", None, "EU", None],
    ["D", 54, "DJIBOUTI", "DJIBOUTI", "N", "1", None, "DJ", None, "AF", None],
    ["D", 55, "DOMINICA", "DOMINICA", "N", "4", None, "DM", None, "NA", None],
    ["D", 56, "DOMINICAN REPUBLIC", "DOMINICAN REPUBLIC", "N", "4", None, "DO", None, "NA", None],
    ["D", 57, "ECUADOR", "ECUADOR", "N", "5", None, "EC", None, "SA", None],
    ["D", 58, "EGYPT", "EGYPT", "N", "1", None, "EG", None, "AF", None],
    ["D", 59, "EL SALVADOR", "EL SALVADOR", "N", "4", None, "SV", None, "NA", None],
    ["D", 60, "EQUATORIAL GUINEA", "EQUATORIAL GUINEA", "N", "1", None, "GQ", None, "AF", None],
    ["D", 61, "ERITREA", "ERITREA", "N", "1", None, "ER", None, "AF", None],
    ["D", 62, "ESTONIA", "ESTONIA", "N", "3", None, "EE", None, "EU", None],
    ["D", 63, "ETHIOPIA", "ETHIOPIA", "N", "1", None, "ET", None, "AF", None],
    ["D", 66, "FIJI", "FIJI", "N", "6", None, "FJ", None, "OC", None],
    ["D", 67, "FINLAND", "FINLAND", "N", "3", None, "FI", None, "EU", None],
    ["D", 68, "FRANCE", "FRANCE", "N", "3", None, "FR", None, "EU", None],
    ["D", 71, "GABON", "GABON", "N", "1", None, "GA", None, "AF", None],
    ["D", 72, "GAMBIA", "GAMBIA", "N", "1", None, "GM", None, "AF", None],
    ["D", 74, "GEORGIA", "GEORGIA", "N", "3", None, "GE", None, "EU", None],
    ["D", 75, "GERMANY", "GERMANY", "N", "3", None, "DE", None, "EU", None],
    ["D", 76, "GHANA", "GHANA", "N", "1", None, "GH", None, "AF", None],
    ["D", 78, "GREECE", "GREECE", "N", "3", None, "GR", None, "EU", None],
    ["D", 80, "GRENADA", "GRENADA", "N", "4", None, "GD", None, "NA", None],
    ["D", 83, "GUATEMALA", "GUATEMALA", "N", "4", None, "GT", None, "NA", None],
    ["D", 85, "GUINEA", "GUINEA", "N", "1", None, "GN", None, "AF", None],
    ["D", 86, "GUINEA-BISSAU", "GUINEA-BISSAU", "N", "1", None, "GW", None, "AF", None],
    ["D", 87, "GUYANA", "GUYANA", "N", "5", None, "GY", None, "SA", None],
    ["D", 88, "HAITI", "HAITI", "N", "4", None, "HT", None, "NA", None],
    ["D", 89, "HONDURAS", "HONDURAS", "N", "4", None, "HN", None, "NA", None],
    ["D", 91, "HUNGARY", "HUNGARY", "N", "3", None, "HU", None, "EU", None],
    ["D", 92, "ICELAND", "ICELAND", "N", "3", None, "IS", None, "EU", None],
    ["D", 93, "INDIA", "INDIA", "N", "2", None, "IN", None, "AS", None],
    ["D", 94, "INDONESIA", "INDONESIA", "N", "2", None, "ID", None, "AS", None],
    ["D", 95, "IRAN", "IRAN", "N", "2", None, "IR", None, "AS", None],
    ["D", 96, "IRAQ", "IRAQ", "N", "2", None, "IQ", None, "AS", None],
    ["D", 97, "ISRAEL", "ISRAEL", "N", "2", None, "IL", None, "AS", None],
    ["D", 98, "ITALY", "ITALY", "N", "3", None, "IT", None, "EU", None],
    ["D", 99, "IVORY COAST", "IVORY COAST", "N", "1", None, "CI", None, "AF", None],
    ["D", 100, "JAMAICA", "JAMAICA", "N", "4", None, "JM", None, "NA", None],
    ["D", 101, "JAPAN", "JAPAN", "N", "2", None, "JP", None, "AS", None],
    ["D", 103, "JORDAN", "JORDAN", "N", "2", None, "JO", None, "AS", None],
    ["D", 104, "KAZAKHSTAN", "KAZAKHSTAN", "N", "2", None, "KZ", None, "AS", None],
    ["D", 105, "KENYA", "KENYA", "N", "1", None, "KE", None, "AF", None],
    ["D", 106, "KIRIBATI", "KIRIBATI", "N", "6", None, "KI", None, "OC", None],
    ["D", 107, "KUWAIT", "KUWAIT", "N", "2", None, "KW", None, "AS", None],
    ["D", 108, "KYRGYZSTAN", "KYRGYZSTAN", "N", "2", None, "KG", None, "AS", None],
    ["D", 109, "LAOS", "LAOS", "N", "2", None, "LA", None, "AS", None],
    ["D", 110, "LATVIA", "LATVIA", "N", "3", None, "LV", None, "EU", None],
    ["D", 111, "LEBANON", "LEBANON", "N", "2", None, "LB", None, "AS", None],
    ["D", 112, "LESOTHO", "LESOTHO", "N", "1", None, "LS", None, "AF", None],
    ["D", 113, "LIBERIA", "LIBERIA", "N", "1", None, "LR", None, "AF", None],
    ["D", 114, "LIBYA", "LIBYA", "N", "1", None, "LY", None, "AF", None],
    ["D", 115, "LIECHTENSTEIN", "LIECHTENSTEIN", "N", "3", None, "LI", None, "EU", None],
    ["D", 116, "LITHUANIA", "LITHUANIA", "N", "3", None, "LT", None, "EU", None],
    ["D", 117, "LUXEMBOURG", "LUXEMBOURG", "N", "3", None, "LU", None, "EU", None],
    ["D", 119, "MACEDONIA", "MACEDONIA", "N", "3", None, "MK", None, "EU", None],
    ["D", 120, "MADAGASCAR", "MADAGASCAR", "N", "1", None, "MG", None, "AF", None],
    ["D", 122, "MALAWI", "MALAWI", "N", "1", None, "MW", None, "AF", None],
    ["D", 123, "MALAYSIA", "MALAYSIA", "N", "2", None, "MY", None, "AS", None],
    ["D", 124, "MALDIVES", "MALDIVES", "N", "2", None, "MV", None, "AS", None],
    ["D", 125, "MALI", "MALI", "N", "1", None, "ML", None, "AF", None],
    ["D", 126, "MALTA", "MALTA", "N", "3", None, "MT", None, "EU", None],
    ["D", 127, "MARSHALL ISLANDS", "MARSHALL ISLANDS", "N", "6", None, "MH", None, "OC", None],
    ["D", 129, "MAURITANIA", "MAURITANIA", "N", "1", None, "MR", None, "AF", None],
    ["D", 130, "MAURITIUS", "MAURITIUS", "N", "1", None, "MU", None, "AF", None],
    ["D", 132, "MEXICO", "MEXICO", "N", "4", None, "MX", None, "NA", None],
    ["D", 133, "MICRONESIA", "MICRONESIA", "N", "6", None, "FM", None, "OC", None],
    ["D", 134, "MOLDOVA", "MOLDOVA", "N", "3", None, "MD", None, "EU", None],
    ["D", 135, "MONACO", "MONACO", "N", "3", None, "MC", None, "EU", None],
    ["D", 136, "MONGOLIA", "MONGOLIA", "N", "2", None, "MN", None, "AS", None],
    ["D", 138, "MOROCCO", "MOROCCO", "N", "1", None, "MA", None, "AF", None],
    ["D", 139, "MOZAMBIQUE", "MOZAMBIQUE", "N", "1", None, "MZ", None, "AF", None],
    ["D", 140, "BURMA", "BURMA", "N", "2", None, "MM", None, "AS", None],
    ["D", 141, "NAMIBIA", "NAMIBIA", "N", "1", None, "NA", None, "AF", None],
    ["D", 142, "NAURU", "NAURU", "N", "6", None, "NR", None, "OC", None],
    ["D", 143, "NEPAL", "NEPAL", "N", "2", None, "NP", None, "AS", None],
    ["D", 144, "NETHERLANDS", "NETHERLANDS", "N", "3", None, "NL", None, "EU", None],
    ["D", 147, "NEW ZEALAND", "NEW ZEALAND", "N", "6", None, "NZ", None, "OC", None],
    ["D", 148, "NICARAGUA", "NICARAGUA", "N", "4", None, "NI", None, "NA", None],
    ["D", 149, "NIGER", "NIGER", "N", "1", None, "NE", None, "AF", None],
    ["D", 150, "NIGERIA", "NIGERIA", "N", "1", None, "NG", None, "AF", None],
    ["D", 152, "NORTH KOREA", "NORTH KOREA", "N", "2", None, "KP", None, "AS", None],
    ["D", 154, "NORWAY", "NORWAY", "N", "3", None, "NO", None, "EU", None],
    ["D", 155, "OMAN", "OMAN", "N", "2", None, "OM", None, "AS", None],
    ["D", 156, "PAKISTAN", "PAKISTAN", "N", "2", None, "PK", None, "AS", None],
    ["D", 157, "PALAU", "PALAU", "N", "6", None, "PW", None, "OC", None],
    ["D", 159, "PANAMA", "PANAMA", "N", "4", None, "PA", None, "NA", None],
    ["D", 160, "PAPUA NEW GUINEA", "PAPUA NEW GUINEA", "N", "6", None, "PG", None, "OC", None],
    ["D", 161, "PARAGUAY", "PARAGUAY", "N", "5", None, "PY", None, "SA", None],
    ["D", 162, "PERU", "PERU", "N", "5", None, "PE", None, "SA", None],
    ["D", 163, "PHILIPPINES", "PHILIPPINES", "N", "2", None, "PH", None, "AS", None],
    ["D", 164, "POLAND", "POLAND", "N", "3", None, "PL", None, "EU", None],
    ["D", 165, "PORTUGAL", "PORTUGAL", "N", "3", None, "PT", None, "EU", None],
    ["D", 167, "QATAR", "QATAR", "N", "2", None, "QA", None, "AS", None],
    ["D", 168, "REPUBLIC OF IRELAND", "REPUBLIC OF IRELAND", "N", "3", None, "IE", None, "EU", None],
    ["D", 170, "ROMANIA", "ROMANIA", "N", "3", None, "RO", None, "EU", None],
    ["D", 171, "RUSSIA", "RUSSIA", "N", "3", None, "RU", None, "EU", None],
    ["D", 172, "RWANDA", "RWANDA", "N", "1", None, "RW", None, "AF", None],
    ["D", 174, "ST KITTS-NEVIS", "ST KITTS-NEVIS", "N", "4", None, "KN", None, "NA", None],
    ["D", 175, "ST LUCIA", "ST LUCIA", "N", "4", None, "LC", None, "NA", None],
    ["D", 176, "ST VINCENT AND GRENADINES", "ST VINCENT AND GRENADINES", "N", "4", None, "VC", None, "NA", None],
    ["D", 177, "SAMOA", "SAMOA", "N", "6", None, "WS", None, "OC", None],
    ["D", 178, "SAN MARINO", "SAN MARINO", "N", "3", None, "SM", None, "EU", None],
    ["D", 179, "SAO TOME AND PRINCIPE", "SAO TOME AND PRINCIPE", "N", "1", None, "ST", None, "AF", None],
    ["D", 180, "SAUDI ARABIA", "SAUDI ARABIA", "N", "2", None, "SA", None, "AS", None],
    ["D", 181, "SENEGAL", "SENEGAL", "N", "1", None, "SN", None, "AF", None],
    ["D", 182, "SEYCHELLES", "SEYCHELLES", "N", "1", None, "SC", None, "AF", None],
    ["D", 183, "SIERRA LEONE", "SIERRA LEONE", "N", "1", None, "SL", None, "AF", None],
    ["D", 184, "SINGAPORE", "SINGAPORE", "N", "2", None, "SG", None, "AS", None],
    ["D", 185, "SLOVAKIA", "SLOVAKIA", "N", "3", None, "SK", None, "EU", None],
    ["D", 186, "SLOVENIA", "SLOVENIA", "N", "3", None, "SI", None, "EU", None],
    ["D", 187, "SOLOMON ISLANDS", "SOLOMON ISLANDS", "N", "6", None, "SB", None, "OC", None],
    ["D", 188, "SOMALIA", "SOMALIA", "N", "1", None, "SO", None, "AF", None],
    ["D", 189, "SOUTH AFRICA", "SOUTH AFRICA", "N", "1", None, "ZA", None, "AF", None],
    ["D", 190, "SOUTH KOREA", "SOUTH KOREA", "N", "2", None, "KR", None, "AS", None],
    ["D", 191, "SPAIN", "SPAIN", "N", "3", None, "ES", None, "EU", None],
    ["D", 192, "SRI LANKA", "SRI LANKA", "N", "2", None, "LK", None, "AS", None],
    ["D", 193, "SUDAN", "SUDAN", "N", "1", None, "SD", None, "AF", None],
    ["D", 194, "SURINAM", "SURINAM", "N", "5", None, "SR", None, "SA", None],
    ["D", 195, "SWAZILAND", "SWAZILAND", "N", "1", None, "SZ", None, "AF", None],
    ["D", 196, "SWEDEN", "SWEDEN", "N", "3", None, "SE", None, "EU", None],
    ["D", 197, "SWITZERLAND", "SWITZERLAND", "N", "3", None, "CH", None, "EU", None],
    ["D", 198, "SYRIA", "SYRIA", "N", "2", None, "SY", None, "AS", None],
    ["D", 200, "TAJIKISTAN", "TAJIKISTAN", "N", "2", None, "TJ", None, "AS", None],
    ["D", 201, "TANZANIA", "TANZANIA", "N", "1", None, "TZ", None, "AF", None],
    ["D", 202, "THAILAND", "THAILAND", "N", "2", None, "TH", None, "AS", None],
    ["D", 204, "TOGO", "TOGO", "N", "1", None, "TG", None, "AF", None],
    ["D", 205, "TONGA", "TONGA", "N", "6", None, "TO", None, "OC", None],
    ["D", 206, "TRINIDAD AND TOBAGO", "TRINIDAD AND TOBAGO", "N", "4", None, "TT", None, "NA", None],
    ["D", 207, "TUNISIA", "TUNISIA", "N", "1", None, "TN", None, "AF", None],
    ["D", 208, "TURKEY", "TURKEY", "N", "2", None, "TR", None, "AS", None],
    ["D", 209, "TURKMENISTAN", "TURKMENISTAN", "N", "2", None, "TM", None, "AS", None],
    ["D", 211, "TUVALU", "TUVALU", "N", "6", None, "TV", None, "OC", None],
    ["D", 212, "UGANDA", "UGANDA", "N", "1", None, "UG", None, "AF", None],
    ["D", 213, "UKRAINE", "UKRAINE", "N", "3", None, "UA", None, "EU", None],
    ["D", 214, "UNITED ARAB EMIRATES", "UNITED ARAB EMIRATES", "N", "2", None, "AE", None, "AS", None],
    ["D", 216, "UNITED STATES OF AMERICA", "UNITED STATES OF AMERICA", "N", "4", None, "US", None, "NA", None],
    ["D", 217, "URUGUAY", "URUGUAY", "N", "5", None, "UY", None, "SA", None],
    ["D", 218, "UZBEKISTAN", "UZBEKISTAN", "N", "2", None, "UZ", None, "AS", None],
    ["D", 219, "VANUATU", "VANUATU", "N", "6", None, "VU", None, "OC", None],
    ["D", 221, "VENEZUELA", "VENEZUELA", "N", "5", None, "VE", None, "SA", None],
    ["D", 222, "VIETNAM", "VIETNAM", "N", "2", None, "VN", None, "AS", None],
    ["D", 224, "YEMEN", "YEMEN", "N", "2", None, "YE", None, "AS", None],
    ["D", 225, "SERBIA", "SERBIA", "N", "3", None, "RS", None, "EU", None],
    ["D", 226, "DEMOCRATIC REPUBLIC OF THE CONGO", "CONGO DEMOCRATIC REPUBLIC", "N", "1", None, "CD", None, "AF", None],
    ["D", 227, "ZAMBIA", "ZAMBIA", "N", "1", None, "ZM", None, "AF", None],
    ["D", 228, "ZIMBABWE", "ZIMBABWE", "N", "1", None, "ZW", None, "AF", None],
    ["D", 233, "MONTENEGRO", "MONTENEGRO", "N", "3", None, "ME", None, "EU", None],
    ["D", 234, "SCOTLAND", "SCOTLAND", "N", "3", "S92000003", "GB", "GB-SCT", "EU", None],
    ["D", 235, "NORTHERN IRELAND", "NORTHERN IRELAND", "N", "3", "N92000002", "GB", "GB-NIR", "EU", None],
    ["D", 236, "ANTARCTICA", "ANTARCTICA", "N", "7", None, "AQ", None, "AN", None],
    ["D", 237, "TIMOR-LESTE", "TIMOR-LESTE", "N", "2", None, "TL", None, "AS", None],
    ["D", 238, "OCCUPIED PALESTINIAN TERRITORIES", "PALESTINE", "N", "2", None, "PS", None, "AS", None],
    ["D", 239, "KOSOVO", "KOSOVO", "N", "3", None, "XK", None, "EU", None],
    ["D", 240, "AKROTIRI AND DHEKELIA", "AKROTIRI AND DHEKELIA", "N", "3", None, "AX", None, "EU", None],
    ["D", 241, "AMERICAN SAMOA", "AMERICAN SAMOA", "N", "6", None, "AS", None, "OC", None],
    ["D", 242, "ANGUILLA", "ANGUILLA", "N", "4", None, "AI", None, "NA", None],
    ["D", 243, "ARUBA", "ARUBA", "N", "4", None, "AW", None, "NA", None],
    ["D", 244, "BERMUDA", "BERMUDA", "N", "4", None, "BM", None, "NA", None],
    ["D", 245, "BRITISH INDIAN OCEAN TERRITORY", "BRITISH INDIAN OCEAN TERRITORY", "N", "2", None, "IO", None, "AS", None],
    ["D", 246, "BRITISH VIRGIN ISLANDS", "BRITISH VIRGIN ISLANDS", "N", "4", None, "VG", None, "NA", None],
    ["D", 247, "CAYMAN ISALNDS", "CAYMAN ISALNDS", "N", "4", None, "KY", None, "NA", None],
    ["D", 248, "CHRISTMAS ISLAND", "CHRISTMAS ISLAND", "N", "2", None, "CX", None, "AS", None],
    ["D", 249, "CLIPPERTON ISLAND", "CLIPPERTON ISLAND", "N", "4", None, "CP", None, "NA", None],
    ["D", 250, "COCOS (KEELING) ISLANDS", "COCOS (KEELING) ISLANDS", "N", "2", None, "CC", None, "AS", None],
    ["D", 251, "COOK ISLANDS", "COOK ISLANDS", "N", "6", None, "CK", None, "OC", None],
    ["D", 252, "EASTER  ISLAND", "EASTER  ISLAND", "N", "6", None, "CL", None, "OC", None],
    ["D", 253, "FALKLAND ISLANDS", "FALKLAND ISLANDS", "N", "5", None, "FK", None, "SA", None],
    ["D", 254, "FAROE ISLANDS", "FAROE ISLANDS", "N", "3", None, "FO", None, "EU", None],
    ["D", 255, "FRENCH GUYANA", "FRENCH GUYANA", "N", "5", None, "GF", None, "SA", None],
    ["D", 256, "FRENCH POLYNESIA", "FRENCH POLYNESIA", "N", "6", None, "PF", None, "OC", None],
    ["D", 257, "GIBRALTAR", "GIBRALTAR", "N", "3", None, "GI", None, "EU", None],
    ["D", 258, "GREENLAND", "GREENLAND", "N", "4", None, "GL", None, "NA", None],
    ["D", 259, "GUADELOUPE", "GUADELOUPE", "N", "4", None, "GP", None, "NA", None],
    ["D", 260, "GUAM", "GUAM", "N", "6", None, "GU", None, "OC", None],
    ["D", 261, "GUERNSEY", "GUERNSEY", "N", "3", None, "GG", None, "EU", None],
    ["D", 262, "HONG KONG", "HONG KONG", "N", "2", None, "HK", None, "AS", None],
    ["D", 263, "ISLE OF MAN", "ISLE OF MAN", "N", "3", None, "IM", None, "EU", None],
    ["D", 264, "JAN MAYEN", "JAN MAYEN", "N", "3", None, "SJ", None, "EU", None],
    ["D", 265, "JERSEY", "JERSEY", "N", "3", None, "JE", None, "EU", None],
    ["D", 266, "JUAN FERNANDEZ ISLANDS", "JUAN FERNANDEZ ISLANDS", "N", "6", None, "CL", None, "OC", None],
    ["D", 267, "MACAU", "MACAU", "N", "2", None, "MO", None, "AS", None],
    ["D", 268, "MARTINIQUE", "MARTINIQUE", "N", "4", None, "MQ", None, "NA", None],
    ["D", 269, "MAYOTTE", "MAYOTTE", "N", "1", None, "YT", None, "AF", None],
    ["D", 270, "MONTSERRAT", "MONTSERRAT", "N", "4", None, "MS", None, "NA", None],
    ["D", 271, "NETHERLANDS ANTILLES", "NETHERLANDS ANTILLES", "N", "4", None, "AN", None, "NA", None],
    ["D", 272, "NEW CALEDONIA", "NEW CALEDONIA", "N", "6", None, "NC", None, "OC", None],
    ["D", 273, "NIUE", "NIUE", "N", "6", None, "NU", None, "OC", None],
    ["D", 274, "NORFOLK ISLAND", "NORFOLK ISLAND", "N", "6", None, "NF", None, "OC", None],
    ["D", 275, "NORTHERN MARIANA ISLAND", "NORTHERN MARIANA ISLAND", "N", "6", None, "MP", None, "OC", None],
    ["D", 276, "PITCAIRN ISLANDS", "PITCAIRN ISLANDS", "N", "6", None, "PN", None, "OC", None],
    ["D", 277, "PUERTO RICO", "PUERTO RICO", "N", "4", None, "PR", None, "NA", None],
    ["D", 278, "REUNION", "REUNION", "N", "1", None, "RE", None, "AF", None],
    ["D", 279, "ROSS DEPENDENCY", "ROSS DEPENDENCY", "N", "7", None, "AQ", None, "AN", None],
    ["D", 280, "ST BARTHELEMY", "ST BARTHELEMY", "N", "4", None, "BL", None, "NA", None],
    ["D", 281, "ST HELENA", "ST HELENA", "N", "1", None, "SH", None, "AF", None],
    ["D", 282, "ST MARTIN", "ST MARTIN", "N", "4", None, "MF", None, "NA", None],
    ["D", 283, "ST PIERRE AND MIQUELON", "ST PIERRE AND MIQUELON", "N", "4", None, "PM", None, "NA", None],
    ["D", 284, "SOUTH GEORGIA", "SOUTH GEORGIA", "N", "5", None, "GS", None, "SA", None],
    ["D", 285, "SVALBARD", "SVALBARD", "N", "3", None, "SJ", None, "EU", None],
    ["D", 286, "TAIWAN", "TAIWAN", "N", "2", None, "TW", None, "AS", None],
    ["D", 287, "TOKELAU", "TOKELAU", "N", "6", None, "TK", None, "OC", None],
    ["D", 288, "TURKS AND CAICOS ISLANDS", "TURKS AND CAICOS ISLANDS", "N", "4", None, "TC", None, "NA", None],
    ["D", 289, "U.S. VIRGIN ISLANDS", "U.S. VIRGIN ISLANDS", "N", "4", None, "VI", None, "NA", None],
    ["D", 290, "WALLIS AND FUTUNA", "WALLIS AND FUTUNA", "N", "6", None, "WF", None, "OC", None],
    ["D", 293, "REPUBLIC OF SOUTH SUDAN", "SOUTH SUDAN", "N", "1", None, "SS", None, "AF", None],
    ["E", 1, "AFRICA", "AFRICA", "N", None, None, None, None, "AF", None],
    ["E", 2, "ASIA", "ASIA", "N", None, None, None, None, "AS", None],
    ["E", 3, "EUROPE", "EUROPE", "N", None, None, None, None, "EU", None],
    ["E", 4, "NORTH AMERICA", "NORTH AMERICA", "N", None, None, None, None, "NA", None],
    ["E", 5, "SOUTH AMERICA", "SOUTH AMERICA", "N", None, None, None, None, "SA", None],
    ["E", 6, "OCEANIA", "OCEANIA", "N", None, None, None, None, "OC", None],
    ["E", 7, "ANTARCTICA", "ANTARCTICA", "N", None, None, None, None, "AN", None],
]
